name: Object filter
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo $ACTION_EVENT
        env:
          ACTION_EVENT: ${{toJson(github.event)}}
      - run: echo $VALUE
        env:
          VALUE: ${{toJson(github.event.*)}}
